Acme\Bundle\AppBundle\Entity\Category:
    type: entity
    table: pim_catalog_category
    repositoryClass: Akeneo\Bundle\ClassificationBundle\Doctrine\ORM\Repository\CategoryRepository
    fields:
        description:
            type: string
            length: 255
            nullable: true
