extensions:
    pim-menu-reference_data-item-supplier:
        module: pim/menu/item
        parent: pim-menu-reference_data-navigation-block
        position: 10
        config:
            title: app.menu.item.reference_data.supplier
            to: pim_customentity_index
            routeParams:
                customEntityName: supplier
