AppBundle\Entity\CategoryTranslation:
    type: entity
    table: pim_catalog_category_translation
    changeTrackingPolicy: DEFERRED_EXPLICIT
    uniqueConstraints:
        locale_foreign_key_idx:
            columns:
                - locale
                - foreign_key
    fields:
        description:
            type: text
            nullable: true
